### ISSUE TITLE
MetaWorld Proprioception

### ISSUE THREAD

**Issue by mathiasKorte** [facebookresearch/eai-vc#18]
I see in your code that the default values for using proprioception in addition to RGBs are 
- False for DMCS https://github.com/facebookresearch/eai-vc/blob/76fe35e87b1937168f1ec4b236e863451883eaf3/cortexbench/mujoco_vc/visual_imitation/config/DMC_BC_config.yaml#L38
- True for MetaWorld https://github.com/facebookresearch/eai-vc/blob/76fe35e87b1937168f1ec4b236e863451883eaf3/cortexbench/mujoco_vc/visual_imitation/config/Metaworld_BC_config.yaml#L38-L39

I am surprised by the latter because you report big improvements of PVRs over randomly initialised encoders for MetaWorld. This indicates that MetaWorld is difficult from the vision-perspective. But in my opinion, adding proprioception ( ie all information about the gripper) means that only the slight randomisation of the object-to-grab has to be visually detected. 
Considering the easy camera perspective this should be trivial and result in equal performances of all possible vision encoders.

**Comment by aravindr93** [comment]
Hi @mathiasKorte 

We do use proprioception for the Metaworld results. Please note that our evaluation tasks are not just grasping, but we consider several metaworld tasks. Furthermore, we are in the low-shot imitation learning setting where we are provided only `~25` demonstrations. In practice, this makes the tasks non-trivial, and indeed leads to a differentiation in performance between different models. One can of course train explicit object detectors and use that in the policy architecture somehow. But that is a very different and more restrictive/modular approach compared to simply using flexible visual features and training policy heads on top of it.
