### ISSUE TITLE
How to render on cpu

### ISSUE THREAD

**Issue by datonefaridze** [facebookresearch/eai-vc#4]
Hi, my laptop has only i GPU, as i have noticed rendering is done on gpu, I don't know if my error is somehow connected to it or not, but with this config:
```
{'env_name': 'relocate-v0', 'suite': 'adroit', 'device': 'cpu',
               'image_width': 256, 'image_height': 256, 'camera_name': 'vil_camera',
                 'embedding_name': 'vc1_vitl', 'pixel_based': True, 'render_gpu_id': 0, 
                 'seed': 12345, 'history_window': 3, 'add_proprio': False, 'proprio_key': 'None'}
```
it outputs the error:
```
  File "/home/dato/src/my_projects/robotics/eai-vc/cortexbench/mujoco_vc/src/mujoco_vc/gym_wrapper.py", line 65, in observation
    return self.get_image()
  File "/home/dato/src/my_projects/robotics/eai-vc/cortexbench/mujoco_vc/src/mujoco_vc/gym_wrapper.py", line 51, in get_image
    img = self.sim.render(
  File "third_party/mujoco-py/mujoco_py/mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
  File "third_party/mujoco-py/mujoco_py/mjsim.pyx", line 158, in mujoco_py.cymj.MjSim.render
  File "third_party/mujoco-py/mujoco_py/mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
  File "third_party/mujoco-py/mujoco_py/mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "third_party/mujoco-py/mujoco_py/opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
```
code is simple:
```
e = env_constructor(**env_kwargs, fuse_embeddings=fuse_embeddings_flare)
while True:
    e.reset()
    for i in range(100):
        e.step(np.random.rand(30))
        e.render()
```

**Comment by mathfac** [comment]
Hi @datonefaridze,

Thank you for your question. Yes, it is possible to render without a GPU. It seems that you might not have OpenGL installed or it might be improperly configured.

**For macOS**, OpenGL comes preinstalled.

**For Linux**, you can try installing it with the following commands:

```bash
sudo apt-get update
sudo apt-get install libgl1-mesa-glx
sudo apt-get install libgl1-mesa-dri # install software OpenGL renderer
```

If needed, you can force software rendering by setting an environment variable:

```bash
export LIBGL_ALWAYS_SOFTWARE=1
```

Additionally, ensure that the pip package "glfw" is installed. You can install it using the following command:

```bash
pip install glfw
```

I hope this helps! Let me know if you have any further questions.

**Comment by datonefaridze** [comment]
@mathfac sorry but issue still persists:
```
/home/dato/anaconda3/envs/eai-vc/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/dato/anaconda3/envs/eai-vc/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c106detail19maybe_wrap_dim_slowEllb
  warn(f"Failed to load image Python extension: {e}")
/home/dato/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/spaces/box.py:84: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Not using CUDA.
Loading config path: /home/dato/src/my_projects/robotics/eai-vc/vc_models/src/vc_models/conf/model/vc1_vitl.yaml
Found 4 GPUs for rendering. Using device 0.
Creating window glfw
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  184
  Current serial number in output stream:  184
```

**Comment by mathfac** [comment]
To help diagnose the problem, please try running the following script and let us know if it executes without any issues:

```python
import glfw

if glfw.init():
    print("GLFW initialization successful.")
else:
    print("GLFW initialization failed.")
```

It appears that this might be related to a GLFW issue. A solution can be found in this comment on the Metaworld repository: [Issue #170 - Comment](https://github.com/Farama-Foundation/Metaworld/issues/170#issuecomment-662061007).

**Comment by datonefaridze** [comment]
@mathfac hi, i gave up on the issue and went straight to my project. can i use pretrained model on real robots? such as lewansoul xarm? for some reason i have 2  (256, 256) heads and they learn pretty good but they don't generalize (i am doing supervised learning and when i deploy model on robot it fails), so do you think this model can be used in real life  robot?

**Comment by datonefaridze** [comment]
this is config, please ignore unnecessary fields.
```
 'env_kwargs': {'env_name': 'relocate-v0',
  'suite': 'adroit',
  'device': 'cuda',
  'image_width': 256,
  'image_height': 256,
  'camera_name': 'vil_camera',
  'embedding_name': 'vc1_vitl',
  'pixel_based': True,
  'render_gpu_id': 0,
  'seed': 12345,
  'history_window': 3,
  'add_proprio': False,
  'proprio_key': 'None'},
 'bc_kwargs': {'hidden_sizes': '(256, 256)',
  'nonlinearity': 'relu',
  'loss_type': 'MSE',
  'batch_size': 30,
  'lr': 0.0001,
  'dropout': 0.2}
```

**Comment by aravindr93** [comment]
Hi @datonefaridze thanks for the interest!

Regarding the first issue, I agree with Oleksandr that it appears to be an installation of OpenGL issue. This is a bit out of scope for discussion in this repo. Please reach out to the mujoco GitHub page if the issue persists.

About using on robots, yes! Absolutely! VC-1 is designed for use on all EAI agents including physical robots. Several papers have successfully used it (e.g. https://pvrs-sim2real.github.io/).

There isn't anything actionable with this issue at the moment. So I am closing it.
